In [2]:
#import packages
import datetime 
from itertools import product
import logging
import pickle
import numpy as np
import pandas as pd
import scipy as sp
import os
from math import isnan
from sklearn.preprocessing import LabelEncoder
from collections import Counter
import seaborn as sns
import pymc3 as pm  
from theano import tensor as tt
from theano import shared
import arviz as az
import warnings

%matplotlib inline  
#%matplotlib inline is a magic function that renders the figure in a notebook (instead of displaying a dump of the figure object)
from matplotlib import pyplot as plt 
from matplotlib.offsetbox import AnchoredText
from matplotlib.ticker import FuncFormatter, StrMethodFormatter


In [3]:
# Aaron Helper function
def indexall(L):
    poo = []
    for p in L:
        if not p in poo:
            poo.append(p)
    Ix = np.array([poo.index(p) for p in L])
    return poo,Ix

def subindexall(short,long):
    poo = []
    out = []
    for s,l in zip(short,long):
        if not l in poo:
            poo.append(l)
            out.append(s)
    return indexall(out)

match = lambda a, b: [ b.index(x) if x in b else None for x in a ]
grep = lambda s, l: np.array([i for i in l if s in i])

# Function to standardize covariates
def stdise(x):
    return (x-np.mean(x))/(np.std(x)*2)

# Function to mean-centre covariates
def centre(x):
    return (x-np.mean(x))

def invlogit(x):
    return np.exp(x)/(1+np.exp(x))

def gelplot(pj,vector,posy,csize=40,lwd50=7,lwd95=1):
    if np.percentile(vector,2.5)<0 and 0<np.percentile(vector,97.5):
        pj.plot(np.median(vector),posy,'.',markersize=csize,c='grey')
        pj.plot((np.percentile(vector,2.5),np.percentile(vector,97.5)),(posy,posy),linewidth=lwd95,c='grey')
        pj.plot((np.percentile(vector,25),np.percentile(vector,75)),(posy,posy),linewidth=lwd50,c='grey')
    else:
        pj.plot(np.median(vector),posy,'.',markersize=csize,c='black')
        pj.plot((np.percentile(vector,2.5),np.percentile(vector,97.5)),(posy,posy),linewidth=lwd95,c='black')
        pj.plot((np.percentile(vector,25),np.percentile(vector,75)),(posy,posy),linewidth=lwd50,c='black')
        
    if np.percentile(vector,25)<0 and 0<np.percentile(vector,75):
        pj.plot(np.median(vector),posy,'.',markersize=csize,c='white')

In [4]:
os.chdir('C:\\Users\\tmgor\\Dropbox\\Taylor Chapter 3\\Predict_Maturity\\Data\\for model\\in')
os.listdir() # list files in directory

['age_structured_traits.xlsx',
 'car_trait_covariates_v2.xlsx',
 'full_dataset.xlsx',
 'species_level_traits_v1.xlsx',
 'tmp_car_traits.xlsx',
 '~$car_trait_covariates_v2.xlsx',
 '~$full_dataset.xlsx',
 '~$tmp_car_traits.xlsx']

In [6]:
# Import full dataset
data = pd.read_excel('full_dataset.xlsx')
#get rid of species that don't have full complement of trait data
data = data[data.param_complete==0]
data.head()

Species     Stock   Stock_Year  Age  maturity survivorship  \
0  Carcharhinus tilstoni  ABTP-SWP  ABTP-SWP-13    0  0.000000          NaN   
1  Carcharhinus tilstoni  ABTP-SWP  ABTP-SWP-13    1  0.000000          NaN   
2  Carcharhinus tilstoni  ABTP-SWP  ABTP-SWP-13    2  0.000000          NaN   
3  Carcharhinus tilstoni  ABTP-SWP  ABTP-SWP-13    3  0.000000          NaN   
4  Carcharhinus tilstoni  ABTP-SWP  ABTP-SWP-13    4  0.016088          NaN   

   fecundity (num female pups per year) notes model type  source_mat  ...  \
0                                   NaN   NaN        NaN  Harry 2013  ...   
1                                   NaN   NaN        NaN  Harry 2013  ...   
2                                   NaN   NaN        NaN  Harry 2013  ...   
3                                   NaN   NaN        NaN  Harry 2013  ...   
4                                   NaN   NaN        NaN  Harry 2013  ...   

  linf_cm growth_coeff_k lmax_cm age_max_yrs temp_pref  nursery depth_min  \
0   218.0          0.089   166.0        15.0      23.0      0.0       0.0   
1   218.0          0.089   166.0        15.0      23.0      0.0       0.0   
2   218.0          0.089   166.0        15.0      23.0      0.0       0.0   
3   218.0          0.089   166.0        15.0      23.0      0.0       0.0   
4   218.0          0.089   166.0        15.0      23.0      0.0       0.0   

  depth_max depth_ave param_complete  
0     150.0      75.0            0.0  
1     150.0      75.0            0.0  
2     150.0      75.0            0.0  
3     150.0      75.0            0.0  
4     150.0      75.0            0.0  

[5 rows x 37 columns]

In [7]:
# make datafame of only stocks which have age-structured maturity data
# only data rows where SA-mat A
mdata= data[data.SA_mat=='A']
mdata.shape

(505, 37)

In [8]:
# Make an index for stock-years 
# Puts an index value unique to the stock year for each row in df
StockYr, Is = indexall(mdata.Stock_Year.values)
nstocks = len(StockYr)
StockYr

['ABTP-SWP-13',
 'ATSH-GOM-03',
 'ATSH-NWA-07',
 'ATSH-NWA-13',
 'BNOS-GOM-11',
 'BNOS-NWA-07',
 'BNOS-NWA-11',
 'BTIP-GOM-05',
 'BTIP-GOM-12',
 'BTIP-NWA-06',
 'COP-SWA-03',
 'DUS-NWA-06',
 'DUS-NWA-11',
 'FTH-GOM-03',
 'FTH-NWA-07',
 'GRE-SWP-06',
 'NER-I-02',
 'OCW-WCP-12',
 'SAN-NWA-06',
 'SAN-NWA-11',
 'SPIN-WP-05',
 'SPT-SWP-13',
 'WTIP-SWP-06']

In [9]:
#Index of covariates
Sind = np.array([list(mdata.Stock_Year.values).index(S) for S in StockYr])

#make arrays of all the covariates
#put Sind after all of these so they match the length of StockYr
rLMAX = mdata.lmax_cm.values[Sind]
rHAB = mdata.habitat.values[Sind]
rTROPH = mdata.trophic_level.values[Sind]
rOFFSZ = mdata.offspring_size_mm.values[Sind]
#rROFFSZ = mdata.relative_offspring_size.values[Sind]
rLITT = mdata.litter_size.values[Sind]
#RLITT = mdata.relative_litter_size.values[Sind]
rINTR = mdata.interbirth_interval_yrs.values[Sind]
rAMAT = mdata.age_50_maturity.values[Sind]
rLMAT = mdata.length_maturity_cm.values[Sind]
rLINF = mdata.linf_cm.values[Sind]
rK = mdata.growth_coeff_k.values[Sind]
rAMAX = mdata.age_max_yrs.values[Sind]
rDEP = mdata.depth_ave.values[Sind]
rDEPMAX = mdata.depth_max.values[Sind]

In [11]:
rDEPMAX

array([ 150.,  280.,  280.,  280.,   64.,   64.,   64.,  100.,  100.,
        100.,  360.,  400.,  400.,   10.,   10., 1000.,    0.,  230.,
        500.,  500.,  100.,  140.,  330.])

In [19]:
# mean centre all covariates

LMAX = centre(np.log(rLMAX))
TROPH = centre(rTROPH)
OFFSZ = centre(rOFFSZ/100)
LITT = centre(np.log(rLITT))
INTR = centre(rINTR)
LMAT = centre(rLMAT)
LINF = centre(np.log(rLINF))
K = centre(rK)
AMAX = centre(np.log(rAMAX))
DEP = centre(np.log(rDEP))
DEPMAX = centre(np.log(rDEPMAX))


In [28]:
K

array([-0.10663356,  0.43436644,  0.06348635,  0.06348635,  0.09268867,
       -0.01200015, -0.01200015,  0.01588091,  0.01588091,  0.02568212,
       -0.14663356, -0.16143356, -0.16143356,  0.04436644,  0.04436644,
        0.09836644,  0.10236644, -0.09463356, -0.13013437, -0.13013437,
       -0.04463356,  0.14436644, -0.14563356])

In [23]:
np.log(rLMAX)

array([5.11198779, 4.70048037, 4.39814602, 4.39814602, 4.86753445,
       4.86753445, 4.86753445, 5.25227343, 5.25227343, 5.25227343,
       5.6167711 , 5.79605775, 5.79605775, 5.01063529, 5.01063529,
       5.24702407, 4.89034913, 5.65248918, 5.31811999, 5.31811999,
       5.70378247, 4.87519732, 5.07517382])

In [24]:
np.log(rLMAX) - np.mean(np.log(rLMAX))

array([-0.03055991, -0.44206733, -0.74440168, -0.74440168, -0.27501324,
       -0.27501324, -0.27501324,  0.10972573,  0.10972573,  0.10972573,
        0.4742234 ,  0.65351006,  0.65351006, -0.1319124 , -0.1319124 ,
        0.10447638, -0.25219857,  0.50994148,  0.1755723 ,  0.1755723 ,
        0.56123478, -0.26735037, -0.06737388])

In [25]:
np.mean(np.log(rLMAX))

5.142547695286238